targets:
  $default:
    builders:
      json_serializable:
        options:
          generic_argument_factories: true

      freezed:
        options:
          generic_argument_factories: true

      flutter_gen_runner:
        options:
          output: lib/generated/
          line_length: 120
          integrations:
            image: true
            flutter_svg: true
            rive: true
            lottie: true
