name: nodelabs_case
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Utility
  easy_localization: ^3.0.8
  auto_route: ^10.1.0+1
  logger: ^2.6.1

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0

  # Object Mapping & Functional Programming
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  equatable: ^2.0.7

  # Networking
  retrofit: ^4.7.0
  dio: ^5.8.0+1

  # Dependency Injection
  injectable: ^2.5.1
  get_it: ^8.1.0

  # UI
  shadcn_ui: ^0.28.2
  flutter_screenutil: ^5.9.3

  # Storage
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.9.5
  # auto_route_generator: ^10.2.3
  retrofit_generator: ^10.0.1
  injectable_generator: ^2.8.0
  flutter_gen_runner: ^5.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
